using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OdeToFood.Data;
using OdeToFood.Models;

namespace OdeToFood.Services
{
    public class SqlRestaurantData : IRestaurantData
    {
        private OdeToFoodDbContext _context;

        public SqlRestaurantData(OdeToFoodDbContext context)
        {
            _context = context;
        }
        public Restaurant Add(Restaurant restaurant)
        {
            _context.Restaurants.Add(restaurant);
            _context.SaveChanges(); // Better method use this in another method, you might save changes after multiple changes
            return restaurant; // new id property will be generated by sql 
        }

        public Restaurant Get(int id)
        {
            return _context.Restaurants.FirstOrDefault( r => r.Id == id);
        }

        public IEnumerable<Restaurant> GetAll()  // Be carefull if large database IEnumerable is not right choice in millon records (Performance issue) 
        // Choose  IQueryable  instead.
        {
           return _context.Restaurants.OrderBy(r => r.Name);
        }

    }
}